### ISSUE TITLE
Wrong generated css

### ISSUE THREAD

**Issue by frangarcia** [i-net-software/jlessc#15]
Another issue with the generated css:

Input:

``` less
.custom-font(@fontName, @path) {
  @font-face {
    font-family: @fontName;
  }
}

//  For each
.for(@array)   when (default()) {.for-impl_(length(@array))}
.for-impl_(@i) when (@i > 1)    {.for-impl_((@i - 1))}
.for-impl_(@i) when (@i > 0)    {.-each(extract(@array, @i))}

@customFonts: "hello";
@themeBasePath: '';

.importCustomFonts when not (@customFonts = none) {
.for(@customFonts); .-each(@customFont) {
.custom-font(@customFont, @themeBasePath)
}
}
```

generates

``` css
@font-face {
  .importCustomFonts {
    font-family: "hello";
  }
}
```

but is should generate 

``` css
@font-face {
  font-family: "hello";
}
```
