### ISSUE TITLE
@keyframes content within declaration is parsed wrongly

### ISSUE THREAD

**Issue by hwanders** [i-net-software/jlessc#31]
Nesting a \@keyframes block within a declaration block results in bad output CSS:

```less
div {
    @keyframes foobar {
        from { opacity: 1; }
        to { opacity: 0; }
    }
} 
```
gets wrongly transformed to
```less
@keyframes foobar {
  opacity: 1;
  opacity: 0;
}
```
but should be transformed to (something similar like)
```less
@keyframes foobar {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}
```
