### ISSUE TITLE
Unwanted LESS calculations applied on CSS properties with "arithmetic-like" values

### ISSUE THREAD

**Issue by AFaust** [i-net-software/jlessc#32]
When integrating JLessC as an alternative to LESS engine in the Share client of [Alfresco ECM](https://www.alfresco.com/) I encountered an instance where JLessC incorrectly evaluated a valid CSS property value as an arithmetic operation. This problem has affected less.js in the past (i.e. [#146](https://github.com/less/less.js/issues/146)) as well.

The CSS specifications define some properties to allow for value expressions that look like arithmetic operations but should not be treated / evaluated as such. This affects e.g. the ```font``` or ```border-radius``` properties. In my case I have a [vendor provided CSS rule](https://github.com/Alfresco/Aikau/blob/develop/aikau/src/main/resources/alfresco/core/css/Core.css#L30)
```css
.@{alfresco}
{
   font:13px/1.231 Open Sans,arial,helvetica,clean,sans-serif;
}
```
that is processed by JLessC to
```css
.alfresco-share {
  font: 10.5605199px Open Sans, arial, helvetica, clean, sans-serif;
}
```
