### ISSUE TITLE
LessException: Undefine Variable

### ISSUE THREAD

**Issue by olegcherr** [i-net-software/jlessc#34]
Hello again :)

```less
@fz:20px;

body {
	font: @fz/1.2 sans-serif; // LessException: Undefine Variable: @fz/1.2
}
```
