### ISSUE TITLE
Enhance merging Mixins

### ISSUE THREAD

**Issue by tofi86** [i-net-software/jlessc#66]
Hi, I'm currently switching over from https://github.com/marceloverdijk/lesscss-java to your less compiler and had pretty good results so far. Thanks for your great tool!

However, I stumbled upon a small issue which the old compiler solved more elegantly:

Let's say you have a modularized stylesheet where you have a mixin component in one module:

```less
.mixin() {
  color: red;
  font-family: serif;
}
```

and you import this in another stylesheet and extend the mixin:

```less
@import (less) "base.less";

.mixin() {
  font-family: sans-serif;
  font-style: bold;
}

p.class {
  .mixin();
}
```

The old official compiler compiled this to

```css
p.class{
  color:red;
  font-family:sans-serif;
  font-style:bold;
}
```

whereas `jlessc` compiles to

```css
p.class{
  color:red;
  font-family:serif;
  font-family:sans-serif;
  font-style:bold;
}
```

Is there any chance you could eliminate duplicate css properties by taking the css precedence into account so that the 'last one' wins?

Thanks for yur help,

Best regards,
Tobias

**Comment by Horcrux7** [comment]
This can be difficult. It sounds simple because it is a simple sample. But at the point of writing the first  `font-family` it is impossible to decide if the second property will be written. It required a context switch to the second mixin and to evaluate it in this scope.

The other option will be in the formatter output self. For example in the method`CssFormatter.appendProperty`. But this will require many additional and complex string operations to remove the already written `font-family:serif;` I expect that the total performance will be reduce with it. 

The original LessC compiler produce for me the same output.

If maximal file size reducing is for you important then you should ran an additional compressing tool in your build environment. The target of JLessC is performance for a live environment with on the fly CSS generation.

**Comment by tofi86** [comment]
> This can be difficult. It sounds simple because it is a simple sample.

> The target of JLessC is performance for a live environment with on the fly CSS generation.

Okay, got it. Indeed not an easy one...


> The original LessC compiler produce for me the same output.

You're right. I pasted a wrong example to the issue... Sorry for that!

The "merging" indeed only works in the original Less compiler, if certain properties are absolutely identical:

```less
.mixin() {
  color: red;
  font-family: sans-serif;
}
```

and you import this in another stylesheet and extend the mixin:

```less
@import (less) "base.less";

.mixin() {
  font-family: sans-serif;
  font-style: bold;
}

p.class {
  .mixin();
}
```

The old official compiler compiled this to

```css
p.class{
  color:red;
  font-family:sans-serif;
  font-style:bold;
}
```

whereas `jlessc` compiles to

```css
p.class{
  color:red;
  font-family:sans-serif;
  font-family:sans-serif;
  font-style:bold;
}
```

I understand your concerns about speed and the difficulties around merging the mixins and properties.

But maybe there is a chance to eliminate exact duplicates like in this case?
