### ISSUE TITLE
:extend selector compiled to &

### ISSUE THREAD

**Issue by manuelleduc** [i-net-software/jlessc#80]
Hello,
I am currently evaluating a migration to jlessc and I must say I'm quite impressed by the compilation times (especially in comparison with my existing less compiler, about 8 times slower) and would very like to see jlessc integrated in my code base.

Sadly, I encountered a compilation issue that break my css style. Some selectors are replaced by `&` in the resulting css.
For instance:
```css
.table>thead>tr>th,
.table>tbody>tr>th,
.table>tfoot>tr>th,
.table>thead>tr>td,
.table>tbody>tr>td,
.table>tfoot>tr>td,
& {
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #ddd
}
```
instead of:
```css
.table>thead>tr>th,
.table>tbody>tr>th,
.table>tfoot>tr>th,
.table>thead>tr>td,
.table>tbody>tr>td,
.table>tfoot>tr>td,
table>thead>tr>th,
table>tbody>tr>th,
table>tfoot>tr>th,
table>thead>tr>td,
table>tbody>tr>td,
table>tfoot>tr>td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: top;
    border-top: 1px solid #ddd;
}
```

I've started to try to find a reproduction case using jlessc test suite, without success. My best guess is that is is related to the use of `:extend(...)` but using this directive using simpler less files did not cause the issue.
So before doing a deeper debugging I'd like to ask if you have some idea of the root cause if this issue.
If not I'll try to provide a reproduction case.

Thanks.

Some additional information:
- I'm using jlessc 1.10
- I'm using a custom `ReaderFactory`
- I'm using bootstrap 3.4.1 (I saw that the tests are using bootstrap 3.3.1)
