### ISSUE TITLE
Wrong compilation when using max()

### ISSUE THREAD

**Issue by rooboo** [i-net-software/jlessc#83]
The min and max Methods are not compiled correctly.

```css
.my-selector {
width : max(calc(100% - 7em), 7em);
}
```
results in
```css
.my-selector {
width : 7em;
}
```

Also 
```css
.my-selector {
min(7em, calc(100% - 7em));
}
```
results in 
```css
.my-selector {
min: 0em;
}
```
